### ISSUE TITLE
Error on build image

### ISSUE THREAD

**Issue by guilherme-maegava** [azavea/docker-openjdk-gdal#9]
Please,

Help with this issue:

used command:
`GDAL_VERSION=2.3.2 OPENJPEG_VERSION=2.3.0 VARIANT=alpine OPENJDK_VERSION=8 ./scripts/cibuild`

output error:
![image](https://user-images.githubusercontent.com/22353505/69663986-33345e00-1066-11ea-96ba-50a2e217da7a.png)

**Comment by hectcastro** [comment]
Thanks for bringing this issue to our attention, @guilherme-maegava. In the meantime, please feel free to use one of the container images we built and published using the contents of this repository: https://quay.io/repository/azavea/openjdk-gdal?tab=tags

**Comment by rbreslow** [comment]
We [removed](https://github.com/azavea/docker-openjdk-gdal/pull/8) support for Alpine variants of this image because [guidance](https://github.com/docker-library/openjdk/issues/272) from the `docker-openjdk` maintainers is that Alpine is not officially supported by the OpenJDK project for JDKs 8 & 11.

See that Alpine is not included in the build pipeline for these variants of `docker-openjdk`: https://github.com/docker-library/openjdk/blob/664f4953394f3459704e15f09aae014a22c57f33/update.sh#L116.

We think there is a path forward on JDK 8 with [AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-docker), however, I don't think we're going to move on this because we prefer the `slim` variants in production. We may revisit this if we add support for JDK 12+.

Nevertheless, thank you again for surfacing this.
